# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: xenial
language: R
sudo: false
addons:
  apt:
    packages:
      - libnode-dev
r:
#  - oldrel does not work
  - release
  - devel
r_packages:
 - DiagrammeRsvg
cache: packages
latex: false
